print("Welcome to password checker! Here are the requirements for your password:")
print("- At least 8 characters long")
print("- Contains both uppercase and lowercase letters")
print("- Contains at least one digit")
print("- Contains at least one special character")
print("- No palindrones or more than 3 repeated characters in a row")
print("- No more than 3 numbers increasing/decreasing in a row")
password = input("enter a password: ")
password.split()
